# Generated by Django 4.2.7 on 2024-07-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.FileField(default='', upload_to='blogs_content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='autor',
            field=models.CharField(max_length=50),
        ),
    ]
